# Método de Jacobi

In [1]:
import numpy as np
import matplotlib.pyplot as plt

def jacobi(A, b, x0, eps=1e-10, n=500):
    D=np.diag(np.diag(A))
    LU = A - D
    x = x0
    for i in range(n):
        D_inv = np.linalg.inv(D)
        x_anterior = x
        
#Esta es la ecuación que usaremos para el método
        x = (D_inv @ (-LU) @ x) + D_inv @ b
        print("Iteración : ", i, " - x:",x)
        if (np.linalg.norm(x - x_anterior) < eps):
            return (x) 
    print ("No se alcanzó convergencia")           
    return (x)

In [2]:
A = np.array([[7, 1, -1, 2],
              [1, 8, 0, -2],
              [-1, 0, 4, -1],
              [2, -2, -1, 6]])

b = np.array([3, -5, 4, -3])

x0 = np.random.rand(4)
x = jacobi (A, b, x0, 10**(-4), 500)

print ("x: ", x)
print ("b calculado: ", A @ x)
print ("b verdadero: ", b)
print ("Solución de numpy: ", np.linalg.solve (A,b))

Iteración :  0  - x: [ 0.42179734 -0.61306834  1.20383448 -0.5432725 ]
Iteración :  1  - x: [ 0.84334969 -0.81354279  0.96963121 -0.64431614]
Iteración :  2  - x: [ 0.8674009  -0.89149775  1.04975839 -0.89069229]
Iteración :  3  - x: [ 0.96037725 -0.95609819  0.99417715 -0.91133982]
Iteración :  4  - x: [ 0.967565   -0.97288211  1.01225936 -0.97312895]
Iteración :  5  - x: [ 0.99019991 -0.98922786  0.99860901 -0.97810581]
Iteración :  6  - x: [ 0.99200693 -0.99330144  1.00302353 -0.99337442]
Iteración :  7  - x: [ 0.99758197 -0.99734447  0.99965813 -0.99459887]
Iteración :  8  - x: [ 0.99802862 -0.99834746  1.00074578 -0.99836579]
Iteración :  9  - x: [ 0.99940355 -0.99934503  0.99991571 -0.99866773]
Iteración :  10  - x: [ 0.99951374 -0.99959238  1.00018395 -0.99959691]
Iteración :  11  - x: [ 0.99985288 -0.99983844  0.99997921 -0.99967138]
Iteración :  12  - x: [ 0.99988006 -0.99989945  1.00004537 -0.99990057]
Iteración :  13  - x: [ 0.99996371 -0.99996015  0.99999487 -0.99991894]
It

# Método de Gauss Seidel

In [25]:
A = np.array([[7, 1, -1, 2],
              [1, 8, 0, -2],
              [-1, 0, 4, -1],
              [2, -2, -1, 6]])

D = np.diag(np.diag(A))
LU = A - D
#Esta es la ecuación que usaremos para el método
BJ = np.dot(np.linalg.inv(D), -LU)
print (BJ)

[[ 0.         -0.14285714  0.14285714 -0.28571429]
 [-0.125       0.          0.          0.25      ]
 [ 0.25        0.          0.          0.25      ]
 [-0.33333333  0.33333333  0.16666667  0.        ]]


In [26]:
np.linalg.eig(BJ)

(array([ 0.49665002, -0.49665002,  0.16476735, -0.16476735]),
 array([[-0.51557945,  0.47396582,  0.37971893, -0.47940121],
        [ 0.48291663, -0.20535789,  0.03530751, -0.77196737],
        [ 0.09362379, -0.56322998,  0.8995236 ,  0.31911925],
        [ 0.70157249,  0.64494692,  0.21312956,  0.26907947]]))

In [3]:
b = np.array([3, -5, 4, -3])
x0 = np.random.rand(4) 

#Utilizamos este comando solo para llamar valores que teniamos ya escritos
x = jacobi(A, b, x0)

print ("X: ", x)
print ("b calculado : ", np.dot(A,x))
print ("b verdadero: ", b)
print ("Solucion de numpy: ", np.linalg.solve(A,b))

Iteración :  0  - x: [ 0.21420057 -0.52183329  1.41684271 -0.44592551]
Iteración :  1  - x: [ 0.83293243 -0.76325645  0.94206877 -0.50920417]
Iteración :  2  - x: [ 0.81767622 -0.8564176   1.08093207 -0.8750515 ]
Iteración :  3  - x: [ 0.95535038 -0.9459724   0.98565618 -0.87787593]
Iteración :  4  - x: [ 0.95534006 -0.96388778  1.01936861 -0.96949823]
Iteración :  5  - x: [ 0.98889326 -0.98679207  0.99646046 -0.96984785]
Iteración :  6  - x: [ 0.9889926  -0.99107362  1.00476135 -0.99248503]
Iteración :  7  - x: [ 0.99725786 -0.99674533  0.99912689 -0.99256185]
Iteración :  8  - x: [ 0.99728513 -0.99779769  1.001174   -0.99814658]
Iteración :  9  - x: [ 0.99932355 -0.99919729  0.99978464 -0.99816527]
Iteración :  10  - x: [ 0.99933035 -0.99945676  1.00028957 -0.99954284]
Iteración :  11  - x: [ 0.99983314 -0.999802    0.99994688 -0.99954744]
Iteración :  12  - x: [ 0.99983482 -0.999866    1.00007143 -0.99988724]
Iteración :  13  - x: [ 0.99995884 -0.99995116  0.9999869  -0.99988837]
It

# Método SOR

In [31]:
A = np.array([[7, 1, -1, 2],
              [1, 8, 0, -2],
              [-1, 0, 4, -1],
              [2, -2, -1, 6]])

b = np.array([3, -5, 4, -3])

# Valores iniciales
tol = 0.0SS00001        # valor de la tolerancia establecida
error = 100000        # valor inicial de la norma
kmax = 100            # número máximo de iteraciones
n = len(A)            # determina tamaño de A
x = np.zeros(n)       # vector x inicial de ceros
x1 = np.copy(x)       # vector auxiliar de x
k = 1                 # contador inicial de iteraciones
error1=[0]
lambd = 1.1

while k < kmax and error > tol:
    print("iteración: ",k)
    for i in range(n):
        sumatoria = 0
        for j in range(n):
            if i != j:
                sumatoria += (A[i][j] * x[j])
        x[i] = (lambd*((b[i]-sumatoria) / A[i][i]))+(1-lambd)*x[i]
        print("x(",i,"): ",x[i])

    error = np.linalg.norm(x-x1) # cálculo de la norma vectorial
    error1.append(error)         # se genera el vector error para ser graficado
    x1 = np.copy(x)              # actualiza vector solución iteración anterior

    print("  error: ", error1[k])
    print()
    
    k += 1

iteración:  1
x( 0 ):  0.4714285714285714
x( 1 ):  -0.7523214285714287
x( 2 ):  1.2296428571428573
x( 3 ):  -0.7732738095238096
  error:  1.7024119273738814

iteración:  2
x( 0 ):  0.9787661564625854
x( 1 ):  -0.9594985012755102
x( 2 ):  1.0335461096938776
x( 3 ):  -0.9938862067743764
  error:  0.6224447998201033

iteración:  3
x( 0 ):  0.9991089167780206
x( 1 ):  -1.0022463327923803
x( 2 ):  0.9980816342816144
x( 3 ):  -1.0014600045467468
  error:  0.05963469146067364

iteración:  4
x( 0 ):  1.0005995045770888
x( 1 ):  -1.0002592998504671
x( 2 ):  0.9999551990801825
x( 3 ):  -1.0001771080040622
  error:  0.0033654450660565317

iteración:  5
x( 0 ):  1.0000294190326702
x( 1 ):  -1.0000268198330626
x( 2 ):  0.999963865624849
x( 3 ):  -1.0000095347524736
  error:  0.0006381225509977897

iteración:  6
x( 0 ):  0.999998591019468
x( 1 ):  -0.999999746338801
x( 2 ):  1.0000006039109386
x( 3 ):  -0.9999983261724458
  error:  5.6202085553607555e-05

iteración:  7
x( 0 ):  0.9999996698772093
x(