In [39]:
# importando modulos necesarios
import matplotlib.pyplot as plt 
import numpy as np
import scipy.linalg as la

In [14]:
# Ejemplo factorización LU
A = np.array([[0, 0, 0, 6]
             ,[0, 0, 6, 3]
             ,[0, 7, -2, 4]
             ,[21, 9, -3, 5]])

 
P, L, U = la.lu(A)
b = np.array([12, -12, 14, -2])

X = np.linalg.inv(A).dot(b)



In [41]:
# Matriz A
A

array([[ 0,  0,  0,  6],
       [ 0,  0,  6,  3],
       [ 0,  7, -2,  4],
       [21,  9, -3,  5]])

In [42]:
# Matriz de permutación
P

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [43]:
# Matriz triangular inferior
L

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
# Matriz triangular superior
U

array([[21.,  9., -3.,  5.],
       [ 0.,  7., -2.,  4.],
       [ 0.,  0.,  6.,  3.],
       [ 0.,  0.,  0.,  6.]])

In [15]:
# Valores de X
print (X)

[-1.00000000e+00  2.22044605e-16 -3.00000000e+00  2.00000000e+00]


In [ ]:
#Algoritmo Realizado por Ismael Salazar